#! /usr/bin/env python

"""
"""

import sys
import argparse


def main(options):
    """Main program."""
    sys.stdout.writelines(
        xmlline(l.strip()) for l in sys.stdin
    )
    return


def xmlline(fieldname):
    """Field Name -> XML field tag"""
    return '                    <field name="%s"/>\n' % (fieldname,)


def get_options():
    """Get options for the script."""
    parser = argparse.ArgumentParser(
        description="field names on STDIN, XML tags on STDOUT",
    )
    # parser.add_argument() calls here
    options = parser.parse_args()
    # extra processing of options here
    return options

if __name__ == "__main__":
    main(get_options())
